Fixing textureSampleCompare documentation
gpuweb/gpuweb pull request #1052
Opened 2020-09-03 17:28 UTC by ponitka

To use the Lod operand we need the function to be ExplicitLod.

2020-09-04 20:05 UTC, kvark requested changes

2020-09-04 20:05 UTC, kvark commented on wgsl/index.bs
> +  %65 = OpImageSampleDrefExplicitLod %float %sampled_image %coord %depth_reference Lod %float_0
I don't see us having the LOD parameter in `textureSampleCompare`

2020-09-05 03:23 UTC, kvark commented on wgsl/index.bs
> +  %65 = OpImageSampleDrefExplicitLod %float %sampled_image %coord %depth_reference Lod %float_0
Oh I see. So `%float_0` here is meant to be just a `0.0` constant

2020-09-05 03:23 UTC, kvark approved these changes

2020-09-18 22:47 UTC, dj2 approved these changes

2020-09-18 22:49 UTC, merged