Fix grammar inconsistency in read-only storage textures
gpuweb/gpuweb pull request #1059
Opened 2020-09-08 17:02 UTC by dneto0

Fixes #1056

Also, remove ReadOnly and WriteOnly literals in the SPIR-V examples
for declaring image types. Those optional literal qualifiers are only
used for Kernel modules, not Shader modules.

2020-09-08 20:05 UTC, kvark requested changes
The first half of the change is great!
This half, however, is not:
> Also, remove ReadOnly and WriteOnly literals in the SPIR-V examples
for declaring image types. Those optional literal qualifiers are only
used for Kernel modules, not Shader modules.

We still need to specify that these are read-only or write only.
So instead of stripping them away, we should fix them, i.e. "ReadOnly" -> "NonWritable", and "WriteOnly" -> "NonReadable"

actually: not sure how exactly to write this down in this syntax, but we must say that these decorations apply somehow

2020-09-14 16:59 UTC, dj2 approved these changes

2020-09-14 17:00 UTC, dj2 commented
It doesn't look like there is a way to specify Read/Write only in the SPIR-V? At least not that I see.

2020-09-14 17:39 UTC, kvark commented
In SPIR-V the read/write is done via `NonWritable` and `NonReadable` decorations on the global variable.

2020-09-14 17:41 UTC, dj2 commented
Right, so not relevant for OpImageType, but for when the variable is created later. Is the suggestion to make that update here as well?

2020-09-14 18:44 UTC, kvark approved these changes
I suppose this is where the 1:1 correspondence of WGSL to SPIR-V starts to crack a little bit. Saying that `texture_ro_1d` is just an `OpTypeImage` is correct, but it doesn't provide the full picture.
Where do you see it being specified that this will put the `NonWritable` decoration on any global variable of this image type?

2020-09-14 18:47 UTC, dj2 commented
That's a good question. I think in the variable section where we define things we'll need a blurb on `wo` and `ro` textures that says they get `NonWritable` and `NonReadable` annotations in SPIR-V? @dneto0 does that make sense to you?

2020-09-19 19:06 UTC, dneto0 commented
> That's a good question. I think in the variable section where we define things we'll need a blurb on wo and ro textures that says they get NonWritable and NonReadable annotations in SPIR-V? @dneto0 does that make sense to you?

Yes. Exactly. 
This is a place where Kernel and Shader differ.  I don't know why this is the case for images. (??)

Related is what to do for buffers.   SPIR-V for Shader had to match the flexibility in GLSL, where the readonly attribute can apply to individual struct members.
WebGPU doesn't have that flexibility: read-only-ness or write-only-ness applies to the entire buffer or not at all.

We'll restrict the readonly/writeonly  attribute to the whole variable, as suggested.

(This was on my TODO list!)

2020-09-25 14:49 UTC, dneto0 commented
Closing, as this is superceded by #1089 and #1110

2020-09-25 14:49 UTC, closed without merging