createBindGroup: Require a superset of the layout's bindings
gpuweb/gpuweb pull request #1061
Opened 2020-09-09 13:04 UTC by Kangz

This make bindgroup creation require that a superset of the layout's
bindings are specified, instead of exactly the correct set. This will
make code using getBindGroupLayout less likely to break during
development when the pipeline stops statically referencing a binding.

It also matches the rest of the API where we require superset, instead
of exact matches in most cases.

2020-09-09 14:55 UTC, kvark approved these changes
I think this makes sense, as long as those unused bindings are not special-cased in any way (i.e. they still become a part of the usage scope).

2020-09-09 15:48 UTC, Kangz commented
> I think this makes sense, as long as those unused bindings are not special-cased in any way (i.e. they still become a part of the usage scope).

I would have thought that if we didn't special case them, then they wouldn't become part of the scope, because they aren't part of the bindgroup.

2020-09-09 17:30 UTC, kvark commented
> because they aren't part of the bindgroup.

I don't understand. They *are* part of the bind group, regardless of what the bind group layout thinks.

2020-09-09 17:32 UTC, Kangz commented
> I don't understand. They _are_ part of the bind group, regardless of what the bind group layout thinks.

I guess it depends on how you see it. My intuition for bindgroups is that they are slab allocations for a given layout, so they cannot contain anything else than the bindings defined in the layout. All other entries are ignored. But I get the point about how it interacts weirdly with resource usages.

2020-09-09 19:33 UTC, kainino0x commented
I think an entry in a bind group that's not part of the layout is completely unusable. IMO in implementations we wouldn't want to even keep a ref (it'll prevent things from getting freed even when they're not needed). Tracking the unusable bindings could require us to keep those refs (or adds other complexity to track them without the refs). So I'd lean toward not tracking them.

2020-09-09 19:33 UTC, kainino0x approved these changes

2020-09-09 19:38 UTC, kvark commented
Bah, in this case, I have concerns about this.
When I read the code, and I see that there is a bind group created with resource A and then bound in a pass, I want to know that A now is used in the current usage scope. If we agree on the semantic you are suggesting, then it would require me to chase a trace of things:
  1. look up the bind group layout I passed to bind group creation
  2. look up the creation of that bind group layout, and the descriptor passed
  3. search the list for the resource in question

This is a lot of work, and it would make the API less readable. All - for the ease of having implicit pipeline layout? I don't think the complexity (and loss of clarity) would be worth it.

2020-09-09 21:27 UTC, kvark requested changes
Our general approach has been: if user gives us something, we consider it to be used, even if in fact the actual shader or the draw call, end up not needing it. For example, you can bind a group in a render pass, and we include it in the usage scope, regardless of the current or future pipeline layout.

In order to follow this principle, the PR needs to be specified in a way that consider all the bind group resources to be used (and referenced), even if the layout doesn't need them.

2020-09-09 22:11 UTC, kainino0x commented
That's OK with me.

2020-09-10 13:44 UTC, Kangz commented
> When I read the code, and I see that there is a bind group created with resource A and then bound in a pass, I want to know that A now is used in the current usage scope.

Does it matter if A isn't in the usage scope? It shouldn't produce a validation error. However I'm more concerned about the opposite: A starting to be used in the implicit layout, which trickles down to causing a usage scope error when before there were none.

I agree that it would be best that the extra resources be referenced, but I'm a bit worried that it's overhead for not so much usefulness (memory overhead is at least on pointer per bindgroup plus an extra branch on every `setBindGroup`). At this point I'm not sure if the overhead is worth the usability improvement.

2020-09-10 15:26 UTC, kvark commented
Yes, in general making it more likely that your drawing will fail validation when you change a shader, is not something we want. We want to minimize this, and to show errors earlier (shader module creation, pipeline creation, bind group creation, etc).

I don't get the point about overhead though, at all. We are talking specifically about the scenarios where implicit pipeline layout is used. This is a case where users prefer convenience over full control. They don't care about one or two extra pointers per bind group.

2020-09-10 15:34 UTC, Kangz commented
> I don't get the point about overhead though, at all. We are talking specifically about the scenarios where implicit pipeline layout is used. This is a case where users prefer convenience over full control. They don't care about one or two extra pointers per bind group.

The pointer for the extra resources would need to be present on all underlying objects to `GPUBindGroup` no? Otherwise how do we make the difference between one that's created with extra resources, and the others?

2021-02-15 15:47 UTC, Kangz commented
I am no longer considering this, and it could be added later as a non-breaking change if we decide to do it.

2022-03-25 14:22 UTC, closed without merging