Make blending state explicit
gpuweb/gpuweb pull request #1134
Opened 2020-10-05 22:38 UTC by kvark

Writing https://github.com/gpuweb/gpuweb/pull/1132/commits/251649e2a0a6f005e9de9669ba273a197aa7e8fd I realized how awkward our "default" values for blending are:
> |descriptor|.{{GPUColorStateDescriptor/alphaBlend}} and |descriptor|.{{GPUColorStateDescriptor/colorBlend}}
            are either both defaults, or |descriptor|.{{GPUColorStateDescriptor/format}} has
            {{GPUTextureComponentType/"float"}} component type.

I believe the spec would be better if instead of comparing to some "default" this was an explicit "provided" versus "undefined".

2020-10-06 00:37 UTC, kainino0x commented
We chose this because the default values semantically represent what happens when blending is disabled. This would create a difference between unspecified/undefined and `{}` and `{ srcFactor: "one", dstFactor: "zero", operation: "add" }`.

How about instead having a `dfn dfn` which says something like " \<dfn dfn\>blending is enabled\</dfn\> in a GPUBlendDescriptor if it is not equal to `{ srcFactor: "one", dstFactor: "zero", operation: "add" }`" and using that?

2020-10-06 03:10 UTC, kvark commented
> We chose this because the default values semantically represent what happens when blending is disabled.

Right. Except that if your render target is non-blendable, then enabling blending is technically a UB in native APIs.

2020-10-06 03:14 UTC, kainino0x commented
You want to reintroduce the distinction, then? (between blend-disabled and blend-enabled-but-noop)

I have no real feelings either way.

2020-10-06 03:17 UTC, kvark commented
> You want to reintroduce the distinction, then? 

Yes. That's how it's done in all the native APIs. E.g. in Metal blending is an [explicit flag](https://developer.apple.com/documentation/metal/mtlrenderpipelinecolorattachmentdescriptor/1514642-blendingenabled?language=objc).
I don't think it poses any harm or confusion.

2020-10-06 16:51 UTC, kainino0x approved these changes
Sounds good to me. Let's take it to the meeting then.

2020-11-16 20:10 UTC, jdashg requested changes
Needs to spec what happens if only one but not both are undefined. (is blending enabled then?)

2020-11-16 20:13 UTC, kainino0x commented
We could put one extra layer of dictionary in between so there's only one nullable thing.
```ts
{ blend?: { alpha: GPUBlendDescriptor, color: GPUBlendDescriptor }, ... }
```

2020-11-16 22:59 UTC, kainino0x commented
Editors meeting: Agreed to add that extra layer of dictionary.

2020-11-20 21:28 UTC, kvark commented
This is now updated with a separate struct. Please take another look!

2020-11-23 14:28 UTC, Kangz approved these changes

2020-11-23 17:38 UTC, jdashg approved these changes

2020-11-23 19:25 UTC, kainino0x approved these changes

2020-11-23 19:25 UTC, merged