Make the default value of addressMode{U,V,W} align with WebGL
gpuweb/gpuweb pull request #1297
Opened 2020-12-10 07:32 UTC by Jiawei-Shao

This patch sets the default value of GPUSamplerDescriptor.addressMode
to "repeat" which is the same as the one in WebGL and OpenGL ES 2.0
SPEC.

See #1296 for more details.

2020-12-10 15:55 UTC, kvark approved these changes

2020-12-10 15:56 UTC, Kangz commented
DIdn't we try to make default values do the least amount of work though?

2020-12-10 23:44 UTC, kainino0x commented
- GL: Defaults to repeat
- Vulkan: No default but repeat is index 0
- D3D12: No default but repeat is index 0
- Metal: Defaults to clamp-to-edge

2020-12-10 23:47 UTC, kainino0x commented
I have no opinion at all about which should be default. Out of principle I wish we could make the default clamp-to-border-color; alas, #235 says we can't have that.

2020-12-11 19:34 UTC, jdashg requested changes
We're still discussing this.

2021-02-15 15:48 UTC, Kangz commented
Closing since the group decided to not do this.

2021-02-15 15:48 UTC, closed without merging