Add support for hex float literals
gpuweb/gpuweb pull request #1420
Opened 2021-02-05 20:05 UTC by alan-baker

Fixes #709

* Adds literal tokenization to support hex floats

2021-02-16 17:43 UTC, litherum reviewed
Looks like something that’s just 0x7 would be parsed as a float literal and not an int literal?

2021-02-16 18:02 UTC, alan-baker commented
This is the hex float part:
`0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+`

The exponent suffix is non-optional in this tokenization. The parentheses are matched such that the hex-digit-sequences are a combination that must be preceded by 0x and following by the exponent.

Simplifying it:
`0x(_hex_digit_sequence_)(p|P)(+|-)?[0-9]+`

2021-02-16 22:21 UTC, dneto0 requested changes
Please break FLOAT_LITERAL into two rules.

2021-02-16 22:21 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`FLOAT_LITERAL`<td>`-?(([0-9]*.[0-9]+ | [0-9]+.[0-9]*((e|E)(+|-)?[0-9]+)?) | 0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+)`
This is really dense.
I suggest breaking this up into two,  DECIMAL_FLOAT_LITERAL  and HEX_FLOAT_LITERAL.

Then in the 3 other places where  FLOAT_LITERAL is used, replace it by uses of both of those.

2021-02-16 22:21 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`FLOAT_LITERAL`<td>`-?(([0-9]*.[0-9]+ | [0-9]+.[0-9]*((e|E)(+|-)?[0-9]+)?) | 0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+)`
This section needs more exposition about how to actually convert these literals into actual values.
I could take that as a followup.

2021-02-16 22:22 UTC, dneto0 commented
Discussed in the WGSL meeting of [2021-02-16](https://docs.google.com/document/d/1gDaPdTVrZLht9PY4G3VADkaK3Cw2-OJUFzzNBFE2BvM/edit#heading=h.hp3f2zbslxr9).

Consensus to approve the content of this on the understanding that it reuses C99 syntax.

2021-02-17 17:16 UTC, dj2 commented on wgsl/index.bs
> +  <tr><td>`HEX_FLOAT_LITERAL`<td>`-?0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+`
Could we add a `<tr><td>`FLOAT_LITERAL`<td>DECIMAL_FLOAT_LITERAL | HEX_FLOAT_LITERAL and then leave the usages below?

2021-02-20 03:45 UTC, dneto0 approved these changes
Further fixes are already tracked elsewhere.
Approving as this meets the goal of adding hex float literals.

2021-02-20 03:45 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`HEX_FLOAT_LITERAL`<td>`-?0x([0-9a-fA-F]*.?[0-9a-fA-F]+ | [0-9a-fA-F]+.[0-9a-fA-F]*)(p|P)(+|-)?[0-9]+`
Comparing to C99 draft (http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf 6.4.42):

- should allow both 0x and 0X.  This worth raising to the group in a new issue.  I filed #1453
- the significand expression can be simplified to:
      
        ([0-9a-fA-F]*.[0-9a-fA-F]+ | [0-9a-fA-F]+.)

In fact, the same simplification can be applied to the decimal float literal.

- C99 doesn't include the leading minus.

The last two points are already tracked in https://github.com/gpuweb/gpuweb/issues/775

2021-02-20 03:45 UTC, merged