Rewrite explanation of number tokens
gpuweb/gpuweb pull request #1454
Opened 2021-02-20 05:22 UTC by dneto0

- Removes the leading '-' from numeric literals.
  Should allow 'a-5' without needing an extra space.
- Allows scientific notation floats without a period
- Expresses numeric literals in terms of named parts, which is more readable
- Simplifies the with-a-period fraction cases, following C99 example.
- Allows 0x and 0X as the hex prefix
- Adds TODO to explain how a numeric literal is converted into a value
- For SPIR-V mapping, explains that the negation of a signed int literal or
  float literal can be folded into the underlying OpConstant.

Fixes #755, #1453

2021-02-20 20:07 UTC, dneto0 commented
I realized this MR leaves with no way to parse `-2147483648` because the number part is too large to fit in i32.

2021-02-20 22:33 UTC, jdashg commented
I think it could work: What if unsuffixed literals were their own grammar-time supertype with implicit coersion during parsing? Like, don't parse the int until we can merge cases lexed as EXPR MINUS MINUS POSITIVE_LITERAL, and parse them into AstSubtract(EXPR, parse_int(MINUS concat POSITIVE_LITERAL))

2021-02-21 16:58 UTC, dneto0 commented
> I think it could work: 

I'll need time to process that.

In the meantime, I looked at what happens in C.   By my reading of the C99 draft:

- the `2147483648` is its own token, a _decimal constant_
- 6.4.4.1 says the type of a decimal constant (without suffix) is the first of the following into which it fits: `int`, `long int`, `long long int`.  On my x86-64, `int` is 32 bits, `long int` is 64, so the type is `long int`.
- then the negation is a unary arithmetic operation, and the result is also `long int`.

I also looked at what Clang does.
```c
int main() {
  int x = -2147483648;
  return x;
}
```
$ clang -cc1 -ast-dump x.c
in part shows this:
```
    `-DeclStmt 0x7f8e4d892208 <line:3:3, col:22>
      `-VarDecl 0x7f8e4d892150 <col:3, col:12> col:7 x 'int' cinit
        `-ImplicitCastExpr 0x7f8e4d8921f0 <col:11, col:12> 'int' <IntegralCast>
          `-UnaryOperator 0x7f8e4d8921d8 <col:11, col:12> 'long' prefix '-'
            `-IntegerLiteral 0x7f8e4d8921b8 <col:12> 'long' 2147483648
```

So indeed the literal and its negation are `long` but then when used as an initializer for a 32-bit int, there's an implicit conversion down to 32-bits.  There are no warnings about truncation, even when I add `-Wall`

2021-02-22 14:01 UTC, alan-baker requested changes

2021-02-22 22:18 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`BINARY_EXPONENT_PART`<td>`(p|P) (+|-)?` [=digits=]
That's what it's called in the C grammar.

If the _digits_ part evaluates to N then multiply the significand by 2<sup>N</sup>

2021-02-23 03:16 UTC, dneto0 commented on wgsl/index.bs
> +Literal tokens are defined interms of certain character classes:
Fixed in next commit.

2021-02-23 03:16 UTC, dneto0 commented on wgsl/index.bs
> +          `BINARY_EXPONENT_PART ?`
Fixed in next commit.

2021-02-23 03:17 UTC, dneto0 commented on wgsl/index.bs
> +      <br>OpSNegate. If *e* is a `const_literal`, then the negation can be foled into the OpConstant.
Fixed into next commit.

2021-02-25 18:21 UTC, kvark commented on wgsl/index.bs
> +  : const_literal
re:name, can there be non-const literals?

2022-04-26 07:43 UTC, kdashg commented
Do you want to continue this approach? @dneto0

2022-06-27 14:50 UTC, dneto0 commented
This is entirely superceded, except for the TODO.

The spec currently doesn't say how to convert the text of a literal into a scalar or abstract numeric type.  I'll open a separate issue for that.

2022-06-27 14:50 UTC, closed without merging

2022-06-29 17:06 UTC, kdashg commented
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-06-28-minutes#rewrite-explanation-of-number-tokens-1454">WGSL meeting minutes 2022-06-28</a></summary>



* Do we still want this? It sounds like it has some non-editorial parts?
* MM: This is closed.
* DN:  All superceded, except for the TODO.  For the TODO, I filed [https://github.com/gpuweb/gpuweb/issues/3103](https://github.com/gpuweb/gpuweb/issues/3103) as editorial issue.
* 


</details>