Fix uniform struct size requirement
gpuweb/gpuweb pull request #1560
Opened 2021-03-24 21:46 UTC by alan-baker

Fixes #1558

* Only require nested structures in uniform storage class to have a size
  that is a multiple of 16 bytes

2021-03-25 11:07 UTC, ben-clayton commented
After considering this for a while, I'm not sure we need this rule at all.

If I remember correctly, this rule is trying to address here is [15.6.4. Offset and Stride Assignment](https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap15.html#interfaces-resources-layout):

> The Offset decoration of a member must not place it between the end of a structure or an array and the next multiple of the alignment of that structure or array

Unless I've missed something, I think this rule is describing these two use-cases:

```rust
struct Inner {
  a : vec3<f32>;
};
struct UBO {
  inner : Inner;
  x     : f32;
};
```

```rust
struct UBO {
  a : array<vec3<f32>, 1>;
  y : f32;
};
```

However:

[3.4.6.1. Alignment and Size](https://gpuweb.github.io/gpuweb/wgsl.html#alignment-and-size) section states that:

> `SizeOf(struct S)` is equal to `roundUp(AlignOf(S), OffsetOf(S, L) + SizeOf(S, L))`, Where `L` is the last member of the structure

> `SizeOf(array<E, N>)` is equal to `N * roundUp(AlignOf(E), SizeOf(E))`

and [3.4.6.2. Structure Layout Rules](https://gpuweb.github.io/gpuweb/wgsl.html#structure-layout-rules) states:

> <code>OffsetOf(S, M<sub>N</sub>) = roundUp(AlignOf(S, M<sub>N</sub>), OffsetOf(S, M<sub>N-1</sub>) + SizeOf(S, M<sub>N-1</sub>))</code>
> Where M<sub>N</sub> is the current member and M<sub>N-1</sub> is the previous member

So, in both cases `UBO.x` and `UBO.y` cannot be _"placed between the end of a structure or an array and the next multiple of the alignment of that structure or array"_. I do not believe it is possible to violate this rule based on the other rules.

2021-03-25 13:51 UTC, kvark requested changes
Blocking until @ben-clayton 's findings are confirmed :)

2021-04-15 23:42 UTC, alan-baker commented
I agree with @ben-clayton's analysis, so I modified this PR to remove that rule instead.

2021-04-16 20:03 UTC, kvark approved these changes

2021-04-22 18:25 UTC, dneto0 approved these changes

2021-04-22 18:25 UTC, merged