Allow inter-scope shadowing
gpuweb/gpuweb pull request #1561
Opened 2021-03-25 17:49 UTC by alan-baker

Fixes #1556

* Allows identifiers to be reused so long as the end of the scope is
  different
  * practically, this works very much like c-style scoping
  * one difference is that a function parameter can shadow its
    function's name
  * covers resolution when multiple declarations are in scope
* add examples
* function names no longer must be unique
* clarify scope of function parameters
* remove a duplicated note

2021-03-25 18:36 UTC, kvark approved these changes
I thought we are going to stop on allowing the locals to shadow globals.
But this goes way further.

2021-03-25 19:28 UTC, alan-baker commented
I thought we had consensus on this level, but not intra-scope shadowing. In any event, we can modify this if necessary.

2021-03-26 05:37 UTC, dneto0 requested changes
This is really tidy.
Some typos, and a minor fix is required.

2021-03-26 05:37 UTC, dneto0 commented on wgsl/index.bs
> +reference is resolved to the closest preceding in scope declaration.
Somehow I'd hyphenate this instance of "in scope" to be "in-scope". Can fix later.

2021-03-26 05:37 UTC, dneto0 commented on wgsl/index.bs
> +    // Invalid, cannot reuse built-in function names. See [[#builtin-functions]].
link doesn't render correctly. This is essentially verbatim text.
I'd recommend deleting the reference entirely.

2021-03-26 05:37 UTC, dneto0 commented on wgsl/index.bs
> +    // Valid, foo_2 is in scope until the end of the program.
This is a typo.  foo2 is in scope until the end of the function.
(  Because it seems foo_3 correctly is not allowed to shadow.)

2021-03-26 05:37 UTC, dneto0 commented on wgsl/index.bs
> +      // Valid, bar_2 is in scope until the end of the program.
until the end of the function.

2021-03-26 05:37 UTC, dneto0 commented on wgsl/index.bs
> +reference is resolved to the closest preceding in scope declaration.
Earlier the spec says:

> The scope of a declaration is the set of program locations where a use of the declared identifier would denote its associated object.

That "denote" is no longer true.  The identifer denotes the object only if that's the resolved declaration. 

Recommend rewording that first one as:

> The scope of a declaration is the set of program locations where a use of the declared identifier potentially denotes its associated object.

Later:

> When an identifier is used in scope of one or more declarations for that name, the identifier will denote the object of the declaration appearing closest to that use. We say the identifier use resolves to that declaration.

(and make "resolves" a defined term.)

And add

> Note: A declaration always precedes its identifier's scope. Therefore the nearest in scope declaration of an identifier always precedes the use of the identifier.

2021-03-26 05:38 UTC, dneto0 commented on wgsl/index.bs
> +reference is resolved to the closest preceding in scope declaration.
Hm.. I guess my suggested changes below remove that use.   Alas.

2021-03-29 15:22 UTC, dneto0 approved these changes
Thanks!

2021-03-29 15:22 UTC, merged