Define 'composite' type, pin down "plain" type.
gpuweb/gpuweb pull request #1578
Opened 2021-03-30 20:33 UTC by dneto0

2021-03-30 20:34 UTC, dneto0 commented
I almost used this in the upcoming PR for ptr .field and ptr [i].
It seems handy to have around.  Also, it fully pins down the "plain" types.

2021-04-01 15:29 UTC, kvark approved these changes

2021-04-01 15:48 UTC, alan-baker requested changes

2021-04-01 15:48 UTC, alan-baker commented on wgsl/index.bs
> +expressible as a composition of other types.
```suggestion
expressed as a composition of other types.
```

2021-04-01 15:48 UTC, alan-baker commented on wgsl/index.bs
> +The internal non-overlapping parts of the composite type are called <dfn noexport>components</dfn>.
The non-overlapping sounds odd to me. Is this a property of a composite or a precondition?

2021-04-01 18:26 UTC, merged