Add num_workgroups built-in variable
gpuweb/gpuweb pull request #1684
Opened 2021-04-28 14:15 UTC by alan-baker

Fixes #1671

2021-04-28 15:29 UTC, kvark approved these changes

2021-04-29 01:03 UTC, dneto0 approved these changes

2021-04-29 01:07 UTC, dneto0 requested changes
Forgot to ask to tie this to the existing description of a compute shader grid.

2021-04-29 01:07 UTC, dneto0 commented on wgsl/index.bs
> +      <td width="50%">The number of workgroups
Please define this as equal to vec3<u32>( group_count_x, group_count_y, group_count_z ) as those values are defined at the definition of [=compute shader grid=].

2021-04-29 15:53 UTC, dneto0 approved these changes

2021-04-29 15:53 UTC, merged