[editorial] Remove type shorthands
gpuweb/gpuweb pull request #1749
Opened 2021-05-19 15:29 UTC by alan-baker

* Change duplicate signed integer comparisons to have a set of unsigned
  integer comparisons instead
* remove type shorthands and instead spell out explicitly the types

2021-05-19 18:10 UTC, kvark reviewed
Nice!
I'm a bit concerned here about scale-ability of this. Once we add i8, i16, i64, f16, f64, etc, wouldn't we regret not having shortcuts?

2021-05-19 18:16 UTC, alan-baker commented
Maybe? We do define `numeric scalar` and `numeric vector` elsewhere in the spec. So those would be usable in some circumstances. Other definitions might come down to judgement calls, but this way certainly seems clearer at the moment.

2021-05-19 18:37 UTC, kainino0x commented
> I'm a bit concerned here about scale-ability of this. Once we add i8, i16, i64, f16, f64, etc, wouldn't we regret not having shorthands?

It might be an abuse of a bikeshed feature, but perhaps you could use text macros to keep the shorthands without them being visible in the rendered spec text?
https://tabatkins.github.io/bikeshed/#metadata-text-macro

2021-05-19 19:23 UTC, kvark commented
@alan-baker if that's the plan, can we try expressing this in a way that will be scale-able, since we are touching this?

2021-05-19 20:15 UTC, dneto0 requested changes
I recommend doing what @kainino0x suggested: using a Bikeshed macro.

2021-05-19 20:17 UTC, dneto0 commented
> So those would be usable in some circumstances. Other definitions might come down to judgement calls, but this way certainly seems clearer at the moment.

Yep. It's very easy to assume a new scalar type can appear everywhere a similar type appears.  But that isn't always the case.  E.g. when introducing f16 sometimes an IHV might not have the full math library available for it.

2021-05-20 14:17 UTC, alan-baker commented
> > I'm a bit concerned here about scale-ability of this. Once we add i8, i16, i64, f16, f64, etc, wouldn't we regret not having shorthands?
> 
> It might be an abuse of a bikeshed feature, but perhaps you could use text macros to keep the shorthands without them being visible in the rendered spec text?
> https://tabatkins.github.io/bikeshed/#metadata-text-macro

When I look through the docs it seems to be only predefined text macros: https://tabatkins.github.io/bikeshed/#text-macros so I'm not sure that would work.

2021-05-20 14:30 UTC, dneto0 commented
Right. I can't make new custom macros work either.

@alan-baker's suggestion at https://github.com/gpuweb/gpuweb/pull/1749#issuecomment-845105225 looks good to me.  Hey @kvark  and @kainino0x PTAL.  (Also it's purely "editorial" so I could make the call.)

2021-05-20 14:57 UTC, alan-baker commented
> Right. I can't make new custom macros work either.
> 
> @alan-baker's suggestion at [#1749 (comment)](https://github.com/gpuweb/gpuweb/pull/1749#issuecomment-845105225) looks good to me. Hey @kvark and @kainino0x PTAL. (Also it's purely "editorial" so I could make the call.)

It was rather non-obvious, but I got it to work. Need a line like:
>Text Macro: INT i32 or u32

That line should not be followed by an empty line for some reason.

2021-05-20 16:56 UTC, kainino0x commented
> That line should not be followed by an empty line for some reason.

Oh yes, the `metadata` format is funny. It doesn't like blank lines; they're counted as part of the value for the previous key.

2021-05-20 20:53 UTC, dneto0 approved these changes
Thanks! This is way better.

2021-05-20 20:53 UTC, dneto0 commented on wgsl/index.bs
> +    <td>Less than. [=Component-wise=] when |TI| is a vector. (OpULessThan)
Nice catch

2021-05-20 20:53 UTC, dneto0 commented on wgsl/index.bs
> +    <td>Greater than. [=Component-wise=] when |TI| is a vector. (OpUGreaterThan)
again

2021-05-20 20:53 UTC, dneto0 commented on wgsl/index.bs
> +    <td>Greater than or equal. [=Component-wise=] when |TI| is vector. (OpUGreaterThanEqual)
and again.

2021-05-20 20:53 UTC, merged