Match let declarations for inferred types
gpuweb/gpuweb pull request #2053
Opened 2021-08-23 02:23 UTC by mehmetoguzderin

The spec states that module constants can be of inferred type. This PR aims to allow that in grammar by matching the definition of `global_constant_decl`'s with `variable_statement`'s.

2021-09-01 18:28 UTC, dneto0 approved these changes
Thanks!

2021-09-01 18:31 UTC, dneto0 commented
Hmm... I'm cross-checking with the intent of #1944....

2021-09-01 19:09 UTC, dneto0 requested changes
This is tied to the decision in #1944
It needs a group review

2021-09-01 19:39 UTC, kvark commented
@dneto0 
I think we are leaning towards resolving #1944 in the way allows inference. Hence I approved this PR and said it closes #1944.
But if you want to sync with the group on it, sounds good to me as well.

2021-09-08 01:02 UTC, dneto0 commented
The group agreed during the [2021-09-07 meeting](https://docs.google.com/document/d/1NppRkM2UhtpQNwH-6V7Ek1jxzpzLUBEUyHk9Up63l5s/edit#heading=h.hp3f2zbslxr9)

2021-09-08 01:03 UTC, dneto0 approved these changes
The group agreed to this change today, i.e. allow inferring the type of a module-scope let from the type of its initializer.

2021-09-08 01:03 UTC, merged