wgsl: editorial fixes: control flow statements
gpuweb/gpuweb pull request #2095
Opened 2021-09-09 21:13 UTC by dneto0

- More consistently introduce a control flow statment with a definition
  phrased as:

     "A <dfn>FOO</dfn> statement DOES SOMETHING".

- Add cross-references.
- Other editorial cleanups.

2021-09-09 22:03 UTC, kvark approved these changes

2021-09-10 14:00 UTC, alan-baker requested changes

2021-09-10 15:18 UTC, dneto0 commented on wgsl/index.bs
> +An <dfn>if</dfn> statement either executes or skips execution of a [=compound statement=] based on
Agreed.  I'll take the suggestion.

2021-09-10 17:21 UTC, alan-baker approved these changes

2021-09-10 20:13 UTC, merged