Fix fma() description and typo in normalize()
gpuweb/gpuweb pull request #2109
Opened 2021-09-15 01:49 UTC by munrocket

* Not obvious that fma usually with correct rounding, because *inherited from x * y + z* sounds as `RN(RN(x * y) + z)`
* Typo in normalize() definition.

2021-09-15 06:45 UTC, munrocket commented
```rs
d = |RN(a*b+c) - RN(RN(a*b)+c)|
d = |RN(ab+c) - RN(RN(ab)+c)|
d = |RN(ab+c) - RN(0.5*ulp(ab)+ab+c)|
d = max(0.5*ulp(ab), ulp(ab+c))
```
This is not 1 ULP actually, do we need to define it as expression with max()?

2021-09-15 14:52 UTC, kvark approved these changes
Nice!

2021-09-15 15:21 UTC, munrocket commented
Thanks @kvark! I asked for review alan-baker because he wrote this lines in spec with correctness analysis. Yesterday I don't even know what ULP(x) thing is.

2021-09-15 17:53 UTC, kvark approved these changes
whoa, more errors!

2021-09-16 21:23 UTC, dneto0 requested changes

2021-09-16 21:23 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`fma(x, y, z)`<td>1 ULP
I have sad news.

The "inherited from  x *  y + z" looseness originates in GLSL (4.7.1 Range and precision), which flows through to GLSLStd450FMa in Vulkan "Precision of GLSL.std.450 instructions".

Need @alan-baker to review.

2021-09-16 21:26 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td>`fma(x, y, z)`<td>1 ULP
I should say I don't really understand the analysis at https://github.com/gpuweb/gpuweb/pull/2109#issuecomment-919745407 yet

2021-09-16 21:41 UTC, dneto0 commented
Just looking at the last line:

> d = max(0.5*ulp(ab), ulp(ab+c))

The second term is 1 ULP on the FMA, so we can ignore that.

The question is: can 0.5 ulp(ab) be bigger than 1ULP on the infinitely precise answer for  a*b+c.  Seems like we can force that by making a*b big and make the addition cancel out.

Something like:

        a = 0x1p10
        b = -0x1p10
        a*b = -0x1p20

       c = 0x1.00001p20

        a*b-c = 1

This is the C99 program:
```
#include <stdio.h>
#include <math.h>


int main() {
  float a = 0x1p10;
  float b = -0x1p10;
  float ab = a*b;
  float c = 0x1.00001p20;
  printf("a = %f\n", a);
  printf("b = %f\n", b);
  printf("ab = %f\n", ab);
  printf("c = %f\n", c);
  printf("ab-c = %f\n", ab-c);
  printf("fmaf(a,b,c) = %f\n", fmaf(a,b,c));
  return 0;
}
```
This is what I get:

```
$ ./a
a = 1024.000000
b = -1024.000000
ab = -1048576.000000
c = 1048577.000000
ab-c = -2097153.000000
fmaf(a,b,c) = 1.000000
```

So 1 ULPs _relative to the exact result_ is about 2**-23, but the actual error is around 2**22, or around 2**44 ULPs. 

Did I do that right?

2021-09-16 22:22 UTC, dneto0 commented
Given that Vulkan promises so little, it may be better to remove fma from WGSL entirely.

I haven't looked at the conformance tests to see if it *actually* does better than what the spec says.

2021-09-17 07:39 UTC, munrocket commented
> The question is: can 0.5 ulp(ab) be bigger than 1ULP on the infinitely precise answer for ab+c. Seems like we can force that by making ab big and make the addition cancel out.

You right, I will leave this expression as it was. This commit might just fix typos in the table `Accuracy of built-in functions`.

2021-09-17 13:09 UTC, dneto0 approved these changes
Thanks for the fixes!
This would have been very confusing for newcomers.

2021-09-17 13:09 UTC, merged

2021-09-24 06:22 UTC, munrocket commented
It was impossible to specify it in terms of ULP *relative to exact result* as you showed by counter example. But I think I am going in right direction. My body is ready for roasting in new commit or you can discuss it internally.