Added byte value to fillBuffer
gpuweb/gpuweb pull request #2289
Opened 2021-11-10 21:49 UTC by toji

Fixes #2278

Adds a byte value to fillBuffer (defaulting to zero) to place in
the specified buffer range. This is following feedback on the
most recent WebGPU CG call, which Mozilla did not have a
presence at. As such I'd especially appreciate feedback from
@kvark or @jdashg.

2021-11-10 21:58 UTC, kainino0x reviewed
lgtm with mozilla approval

2021-11-10 21:58 UTC, kainino0x commented on spec/index.bs
>          Encode a command into the {{GPUCommandEncoder}} that fills a sub-region of a
```suggestion
        Encode a command into the {{GPUCommandEncoder}} that fills each byte of a sub-region of a
```

2021-11-17 18:16 UTC, toji commented
Pinging @kvark for a post-vacation review.

2021-11-24 13:27 UTC, kvark requested changes
https://github.com/gpuweb/gpuweb/issues/2278#issuecomment-975989974

2021-12-22 11:30 UTC, Kangz commented
Closing since the group went with `clearBuffer` instead.

2021-12-22 11:30 UTC, closed without merging