A block comment must affirmatively end before end of source
gpuweb/gpuweb pull request #2295
Opened 2021-11-11 16:24 UTC by dneto0

2021-11-11 16:26 UTC, mehmetoguzderin requested changes

2021-11-11 16:26 UTC, mehmetoguzderin commented on wgsl/index.bs
> +<div class='example' heading='Example comments'>
If possible please make this 'example wgsl' so that the example is tested. (Due to past constraints we only test such examples.)

2021-11-11 16:27 UTC, dneto0 commented
It wasn't clear to me that #1470 clearly resolved whether a block comment can be terminated by the end of source.

In that discussion [I was against allowing that](https://github.com/gpuweb/gpuweb/pull/1470#issuecomment-810542869) because it works against being able to easily glue together source texts.

2021-11-11 16:30 UTC, mehmetoguzderin approved these changes

2021-11-13 01:32 UTC, alan-baker approved these changes

2021-11-15 18:23 UTC, jdashg commented
> 
> 
> It wasn't clear to me that #1470 clearly resolved whether a block comment can be terminated by the end of source.
> 
> In that discussion [I was against allowing that](https://github.com/gpuweb/gpuweb/pull/1470#issuecomment-810542869) because it works against being able to easily glue together source texts.

I like this rationale. My previous weakly-held opinion was that this should fall under "don't generate errors that don't matter", but yours is a good enough reason for me to want to require strictness here.

2021-11-16 19:12 UTC, merged

2021-11-16 20:04 UTC, jdashg commented
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/WGSL-2021-11-16-Minutes#a-block-comment-must-affirmatively-end-before-end-of-source-2295">WGSL meeting minutes 2021-11-16</a></summary>



* DN: Wasn’t  clear in previous consensus.  Requiring affirmative closing makes it more reliable/easy to glue together snippets.
* **Merge**


</details>

2021-11-16 21:36 UTC, dneto0 commented
I just happened to see that C++14 has a similar requirement:

2.2 Phases of translation, paragraph 3 says

> A source file shall not end in a partial preprocessing token or in a partial comment.12

with footnote 12 saying:

> ...  A partial comment would arise from a source file ending with an unclosed /* comment.

So yay.