wgsl: fold expression semantics text into definition of type rule
gpuweb/gpuweb pull request #2444
Opened 2021-12-21 22:37 UTC by dneto0

Editorial changes only.
Fixes a TODO about describing side effects.

- Move the text about "type rule table" to just after the definition of
  a type rule.  A type rule table is just a bunch of type rules.
- Move the text about expression semantics into the definition of a
  type rule. It belongs there because the semantics is so heavily dependent
  on the other context in the associated type rule.
- Give the the example of side effects as part of the semantics of
  evaluating the expression.
- Eliminate the "Type rule tables" section, because now it would be
  empty.

2021-12-22 15:29 UTC, kvark reviewed
This seems a bit weird to me so far.
So, every expression has a type, and a proper piece of WGSL would have exactly one type rule applied, determining what the type is.
And every expression has semantics, like the side effects.
Why would we want to shove the semantics into the type rule? The semantics seems different from the type, almost orthogonal.

2021-12-24 00:04 UTC, dneto0 commented
> Why would we want to shove the semantics into the type rule? The semantics seems different from the type, almost orthogonal.

It's a judgement call.  I was trying to fix the TODO

> TODO: example: non-result-value effect is any side effect of a function call subexpression.


When I was writing it out, it ended up referencing the type rule preconditions a lot.  There was so much repeating that it ended up feeling shorter / simpler to put it all together.

Also, each type rule in the tables does have three columns, exactly because they are so tightly bound together.

Maybe the solution is to give a new name for the triple (preconditions, type conclusion, semantics), and then say the "type rule" is the first two parts as a pair.

2021-12-24 20:19 UTC, kvark commented
Sounds reasonable (explanation and last suggestion)

2022-01-04 15:55 UTC, alan-baker requested changes

2022-01-04 15:55 UTC, alan-baker commented on wgsl/index.bs
> +* <dfn noexport lt="semantics of an expression">Semantics</dfn>, which is the effect of evaluating the expression,
There are many inconsistencies in the various type tables. Some call these notes (which I think is particularly problematic for this change), description or semantics. I would suggest making the tables consistent (use either description or semantics) and updating this name to match (if description is used).

2022-07-27 18:11 UTC, dneto0 commented
Meh. Consider closing this without any changes.
Except it's a good idea to make the tables consistent about "Notes" vs "Description"

2024-08-16 17:29 UTC, dneto0 commented
This is very out of date.

Also, the tables in the Types chapter use "Description" consistently.

2024-08-16 17:29 UTC, closed without merging