Move all canvas configure validation to getCurrentTexture
gpuweb/gpuweb pull request #2536
Opened 2022-01-26 02:49 UTC by kainino0x

Previously, there was *some* validation inside configure(), but it only
covered a subset of the rules that were later covered by createTexture
inside getCurrentTexture(). This moves all of the validation to
getCurrentTexture() so it's not effectively duplicated.

Resolves an issue where configure() attempted to do device-timeline
validation but actually needed to do it on on the content timeline.

Extracted from #2416.

2022-01-26 21:27 UTC, toji approved these changes
This seems like it's clearly the right thing to do regardless of whether we make the change to using canvas.width/height or not. LGTM!

2022-02-18 19:59 UTC, kvark requested changes
I asked Anne about this issue with validation briefly, and their answer was that we can say that a canvas is invalidated whenever size changes. That means, user would *have to* run `getContext()` again. And that means we can do all the validation there. So let's try to keep it validated early?

2022-04-26 17:56 UTC, kainino0x commented
Want to close this in favor of early validation, but need to extract a few other things from here so they're not lost.

2022-05-03 22:51 UTC, kainino0x commented
Done in #2819

2022-05-03 22:51 UTC, closed without merging