Allow sparse color attachments and ignored FS outputs
gpuweb/gpuweb pull request #2562
Opened 2022-02-03 10:37 UTC by Kangz

Fixes #1250
Fixes #2060

2022-02-04 20:54 UTC, kvark requested changes
blocking on investigation, which wasn't done yet

2022-02-05 02:13 UTC, toji commented
No qualms about the API shape, assuming the group agrees this feature is feasible.

@kvark: Doing a quick review of the linked issues it's not clear to me what needs to be investigated still? https://github.com/gpuweb/gpuweb/issues/1250#issuecomment-1026905842 seems to confirm that it's technically feasible at least.

2022-02-07 08:27 UTC, Kangz commented
Yeah I should have more clearly linked to that investigation. The behavior works on all APIs we targeted, even running with the debug layers.

2022-02-07 21:20 UTC, kainino0x reviewed
I just realized that using nullable here means both `null` and `undefined` work, which is great because I think it should mean _actual_ sparse arrays work (don't have to explicitly specify `null`). OTOH I may prefer @kvark's suggestion to add a `location` member to these dictionaries similar to vertex `attributeLocation`.

Also need to update:

- > For each |colorTarget| in |descriptor|.{{GPURenderPipelineDescriptor/fragment}}.{{GPUFragmentState/targets}}:

- > In alpha-to-coverage mode, an additional <dfn dfn>alpha-to-coverage mask</dfn>
of MSAA samples is generated based on the |alpha| component of the
fragment shader output value of the {{GPURenderPipelineDescriptor/fragment}}.{{GPUFragmentState/targets}}[0].

- Definition of `colorAttachments` should explain how it works

- `derive render targets layout from pass`

2022-02-08 17:13 UTC, kvark reviewed
Investigation approved:)
Considered alternative approach - not going to work out.
So we can proceed with this in principle, although @kainino0x had ideas on making the shape of the API more usable.
One last thing to address

2022-02-08 17:13 UTC, kvark commented on spec/index.bs
> +        - For each non-`null` |colorState| layout descriptor in the list |descriptor|.{{GPUFragmentState/targets}}:
Something needs to be said about the fact that the sets of targets need to match between the render pass and a pipeline. Here, the wording only happen to care about the non-null attachments, which is insufficient.

2022-02-08 22:59 UTC, kainino0x commented
> So we can proceed with this in principle, although @kainino0x had ideas on making the shape of the API more usable.

If we want to allow a `{0: x, 2: y}` syntax we could use a `record<>` but I don't think it's important. Like I said above it introduces "optional" syntax and that's ugly. Maybe we could add it later as a nonbreaking change if we really wanted to.

2022-02-08 23:00 UTC, kainino0x approved these changes
no further comments, happy to go with this design option

2022-02-09 15:52 UTC, Kangz commented
Sorry, I'm not going to be able to address review comments anytime soon. Can someone take over when/if the group decides to go forward with this?

2022-02-09 20:39 UTC, kvark commented
@Kangz I'll push to this PR and merge

2022-02-09 21:52 UTC, kvark approved these changes

2022-02-09 21:52 UTC, kvark commented on spec/index.bs
> +        - For each non-`null` |colorState| layout descriptor in the list |descriptor|.{{GPUFragmentState/targets}}:
Addressed myself in another commit

2022-02-09 22:28 UTC, kainino0x approved these changes

2022-02-09 23:50 UTC, toji approved these changes

2022-02-10 02:32 UTC, merged

2022-02-10 02:37 UTC, kainino0x commented
Ah, merging this closed 2 issues. Are they both fully resolved? #2060 in particular.

2022-02-10 08:23 UTC, Kangz commented
Yeah #2060 is fixed: there's the note, and the [fragment processing description](https://gpuweb.github.io/gpuweb/#fragment-processing) says:

> Set fragment.[colors](https://gpuweb.github.io/gpuweb/#fragment-colors) to the user-specified [pipeline output](https://gpuweb.github.io/gpuweb/wgsl/#pipeline-output) values from the shader.

Which is imprecise bit supports sparse attachments correctly. (ideally it should be a loop that says, for each attachment color, take the value if it is present, or fill with (0, 0, 0, 1)).