Use concise forms for entry point stage attributes.
gpuweb/gpuweb pull request #2652
Opened 2022-03-09 01:58 UTC by jimblandy

`@stage(vertex)` becomes `@vertex`.

`@stage(fragment)` becomes `@fragment`.

`@stage(compute)` becomes `@compute`.

Introduces the new category "pipeline stage attribute".

2022-03-09 15:42 UTC, alan-baker requested changes
Look good, but I think the missing piece is that the stage attributes still need to be mutually exclusive.

2022-03-16 12:56 UTC, alan-baker approved these changes

2022-04-12 16:05 UTC, dneto0 approved these changes
LGTM!

2022-04-12 18:08 UTC, merged

2022-04-13 17:02 UTC, kdashg commented
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-12-minutes#use-concise-forms-for-entry-point-stage-attributes-2652">WGSL meeting minutes 2022-04-12</a></summary>



* Alan: Looks good.
* _Merge_


</details>