[editorial] Add definitions for uniformity tags
gpuweb/gpuweb pull request #2697
Opened 2022-03-25 16:32 UTC by alan-baker

* A definitions for each tag type: call site, function and parameter
* Add tables for the possible values of each tag and the meaning
* Renames some of the tag values for clarity
* Update subsequent uses to link to the new defintions

2022-03-25 20:28 UTC, dneto0 requested changes
This is a nice, mostly mechanical change.

I have two small requests

2022-03-25 20:28 UTC, dneto0 commented on wgsl/index.bs
> +* Create nodes called "RequiredToBeUniform", "MayBeNonUniform", "CF_start", "CF_return", and if the function is non-void a node called "Value_return".
instead of "the function is non-void".... say "if the funciton has a [=return type=]".

2022-03-25 20:28 UTC, dneto0 commented on wgsl/index.bs
> +  <tr><td><dfn noexport>SubsequentControlFlowMayBeNonUniform</dfn>
The "May" here is confusing about which entity is being constrained.
We're trying to say that executing the function may cause subsequent control flow to be nonuniform.
An alternative (to a naive reader), is that it is permissible to have non-uniform control flow executed after a call to this function.

One possibility is to rename the enums:

      SubsequentControlFlowMayBeNonUniform ->  MayCauseNonUniformControlFlow

      ReturnValueMayBeNonUniform -> MayReturnNonUniformValue

Either that, or change the description to say

     Calling this function may cause control flow to be nonuniform immediately after the call site.

I see there is some rhyming with the argument tags.  So maybe the best thing is to just update the description.

2022-03-28 12:17 UTC, ben-clayton reviewed
LGTM, thanks!

2022-03-28 15:01 UTC, merged