[editorial] Change vast majority of must language to link to shader-creation error
gpuweb/gpuweb pull request #2746
Opened 2022-04-11 20:02 UTC by alan-baker

* Clarify must language that would produce a pipeline-creation or
  dyanmic error
* Only a few bare instances of must remain that describe incorrect
  implementations
* Side-effect is that every shader-creation error is now directly linked
  from the shader-creation error definition
* left all must language in notes and examples alone

2022-04-11 20:04 UTC, alan-baker commented
Curious to get other people's opinions on this change. I find it to be a nice set of clarifications with a great side benefit of a having a list of all shader-creation errors linked from the shader-creation error definition.

2022-04-15 18:43 UTC, kdashg commented
I think it's easier to just have a section that says "violations of MUST or MUST NOT result in shader compilation errors", unless we have any strong and common counter-examples?
I think there are so many ways to violate requirements that listing them isn't particularly useful, but maybe other people feel differently?

2022-04-15 18:58 UTC, dj2 commented
Having the links is nice for when you aren't reading the spec linearly. If you don't see the statement about must being a shader compliation error this makes it a lot clearer just by following the link.

2022-04-15 19:06 UTC, kdashg commented
I just don't like when the underlying source text gets hard to read for all the notation we add. (Can you tell that I'm a markdown fan? :))

2022-04-15 20:05 UTC, dj2 commented
I don't usually disagree.  The problem having just read through the entire spec, it's easy to lose track of the meanings of things and want to jump around. The links make it a lot easier to jump to definitions and then back again.

2022-04-19 16:53 UTC, dneto0 requested changes
This is a nice improvement.  It will help readers.

There are some mechanical things to fix.

I have two suggested wordings update to address preëxisting problems.

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +    Each dimension [=shader-creati be at least 1 and at most an upper bound specified by the WebGPU API.
Typo.

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +That is, there can be no cycles among the declarations:
I think I still prefer "must" here...

Hm.  It feels like there's a singular/plural confusion here even in the old text.

How about rewording:

> That is, no cycles can exist among the declarations:

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +It is a [=dynamic error=] if [[#atomic-rmw|Read-modify-write atomics]] that
lower case the "R" here?

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +A `break` statement [=shader-creation error|must not=] placed such that it would exit from a loop's [[#continuing-statement|continuing]] statement.
Pre-existing problem.  "must not *be* placed"...

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  The `offset` expression [=shader-creation error=] be either:
missed the "must" here.

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  Each `offset` component [=shader-creation error=] be at least `-8` and at most `7`. Values outside
and here

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  The `offset` expression [=shader-creation error=] be either:
and here

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  Each `offset` component [=shader-creation error=] be at least `-8` and at most `7`. Values outside
and here

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  The `offset` expression [=shader-creation error=] be either:
here

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +  Each `offset` component [=shader-creation error=] be at least `-8` and at most `7`. Values outside
here

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +Atomic built-in functions `[=shader-creation error=]` not be used in a [=vertex=] shader stage.
here.  Also the backticks should be removed

2022-04-19 16:53 UTC, dneto0 commented on wgsl/index.bs
> +functions [=shader-creation error=] be either [=address spaces/storage=] or [=address spaces/workgroup=].
missing "must"

2022-04-19 16:55 UTC, dneto0 commented on wgsl/index.bs
> +A `break` statement [=shader-creation error|must not=] placed such that it would exit from a loop's [[#continuing-statement|continuing]] statement.
Actually, this may already be fixed in the main branch.

2022-04-19 18:06 UTC, kdashg approved these changes
I don't think it's necessary, but it does what it says. :)

2022-04-20 17:08 UTC, kdashg commented
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-04-19-minutes#editorial-change-vast-majority-of-must-language-to-link-to-shader-creation-error-2746-">WGSL meeting minutes 2022-04-19</a></summary>



* AB: Spec says “must” a lot and it’s almost always shader-creation error.  Link those to the “shader-creation-error”, and adjust the wording in the handful of other places. Nice to be explicit, and the link navigation makes it easier to go through all of them.
* DS: Find it nice to have the link.
* MM: Our definition of “must” is different from that RFC.  Our definition of “must” involves setting error states. That RFC has no concept of error states. Valuable to distinguish between the two.
* AB: There were a few places where it’s defining a contract that are to be fulfilled by the implementation. There were 3 instances.  I left them unlinked.  
* KG: If folks like, it take it.
* MM: Think this patch is good. Think the existing text describing “must” as specified by RFC is sufficient. 
* _Land when editorially ready._


</details>

2022-05-10 02:43 UTC, alan-baker commented
Ping @dneto0

2022-05-10 20:02 UTC, dneto0 approved these changes
Thanks!

2022-05-10 20:02 UTC, merged