Allow creation-time expression in case seletors
gpuweb/gpuweb pull request #2792
Opened 2022-04-25 19:19 UTC by alan-baker

Fixes #2764
Fixes #2787

* Allow switch statement case selectors to be creation-time expressions
* Add missing `@const` qualification to clamp, determinant and transpose
  builtin functions

2022-04-26 03:01 UTC, kdashg requested changes

2022-04-26 03:01 UTC, kdashg commented on wgsl/index.bs
> +    <td class="nowrap">`@const fn`<br>`clamp(`|e|`:` |T| `,` |low|`:` |T| `,` |high|`:` |T|`) -> ` |T|
This looks unrelated?

2022-04-26 07:02 UTC, kdashg commented on wgsl/index.bs
> +    <td class="nowrap">`@const fn`<br>`clamp(`|e|`:` |T| `,` |low|`:` |T| `,` |high|`:` |T|`) -> ` |T|
Oh, it's just not mentioned in the title.

2022-04-26 07:03 UTC, kdashg approved these changes

2022-04-26 07:04 UTC, kdashg commented
@alan-baker wgsl preview build failed?

2022-04-26 13:49 UTC, alan-baker commented
I'm not sure what's up with that failure. I seems to be in an unrelated part of the spec. Still looking.

2022-05-06 15:53 UTC, dneto0 approved these changes
Thanks!

2022-05-06 16:37 UTC, dneto0 requested changes
Looks good, except for the HTML problem.

2022-05-06 16:37 UTC, dneto0 commented on wgsl/index.bs
> +    <td class="nowrap"`@const fn`<br>`transpose(`|e|`:` mat|R|x|C|<|T|> `) -> ` mat|C|x|R|<|T|>
Have to terminate the `td` element before the `@const` text.
That's the reason for the validation failure.

2022-05-06 16:51 UTC, dneto0 approved these changes
Thanks!

2022-05-06 17:11 UTC, merged