Clarify convertability of constant-time expressions
gpuweb/gpuweb pull request #2862
Opened 2022-05-10 21:17 UTC by dneto0

The inferred concrete type for an abstract type depends only
on the type of the constant-time expression, not on its value.

There is already an example illustrating the principle:

      let i32_too_large_2 = 2147483648; // Invalid.

2022-05-10 21:17 UTC, dneto0 commented
cc: @ben-clayton

2022-05-11 00:08 UTC, alan-baker requested changes
Small typo.

2022-05-11 00:08 UTC, alan-baker commented on wgsl/index.bs
> +* |e| is of type |S|, and type |S| is [=feasible automatic conversion|automatically convertable=] to type |T|, as defined below.
```suggestion
* |e| is of type |S|, and type |S| is [=feasible automatic conversion|automatically convertible=] to type |T|, as defined below.
```

2022-05-11 19:48 UTC, alan-baker approved these changes

2022-05-12 21:20 UTC, merged