Generalize invalid memory reference to any originating variable
gpuweb/gpuweb pull request #3129
Opened 2022-07-04 20:53 UTC by dneto0

Fixes: #3128

2022-07-04 20:54 UTC, dj2 approved these changes

2022-07-04 21:07 UTC, alan-baker requested changes

2022-07-04 21:07 UTC, alan-baker commented on wgsl/index.bs
> +    * a value from any [=memory locations|memory location(s)=]
This is insufficient. I get what is being attempted, but to satisfy Vulkan's robust buffer access you have to allow more than just the locations of the variable. The variable might be declared as 128B, but if the buffer bound is 256B you can get values from bytes beyond the 128th.

So maybe the answer is it has to be broken down by address space. Uniform and storage have the behaviour listed, while private, function and workgroup the behaviour your PR suggests.

2022-07-05 11:39 UTC, alan-baker approved these changes

2022-07-05 19:47 UTC, merged