Clean up description of entry point IO
gpuweb/gpuweb pull request #3237
Opened 2022-07-25 19:52 UTC by dneto0

- delete "IO-shareable" section
- define "user-define input datum" and "user-defined output datum"
  - each can be numeric scalar or numeric vector
- constrain the types of entry point formal parameters and return type,
  without having to define a term for that.
- remove redundancies between various sections about inputs and outputs
- Say more clearly in one place that compute shaders don't have
  user-defined inputs or outputs

Fixes: #3033, #3227

2022-07-26 14:43 UTC, alan-baker requested changes
Good overall, but some editorial changes.

2022-07-26 14:43 UTC, alan-baker commented on wgsl/index.bs
>  * Buffer resources
These terms are almost defined below. Maybe just further expanding that text. E.g change "These are the buffer, texture, and sampler resources." to "Variables in the uniform and storage address spaces are the buffer resources and variables in the handle address space are texture or sampler resources.

2022-07-26 14:43 UTC, alan-baker commented on wgsl/index.bs
> +Each [=user-defined input datum|user-defined input=] and [=user-defined output datum|output=] [=shader-creation error|must=] have an explicitly specified IO location.
Nit: factoring user-defined out of the link might be better.
```suggestion
Each user-defined [=user-defined input datum|input=] and [=user-defined output datum|output=] [=shader-creation error|must=] have an explicitly specified IO location.
```

2022-07-26 21:34 UTC, dneto0 commented on wgsl/index.bs
>  * Buffer resources
We can inject the definition of 'XYZ resource' in the 'variable and value declaration feature summary'.

Or alongside 'uniform buffer' and 'storage buffer' definitions.. I'll try this option.

2022-07-26 22:19 UTC, dneto0 commented on wgsl/index.bs
>  * Buffer resources
I've done the latter, but it churned the spec a fair bit, to define 'texture resource' as the *variable* for a texture, similarly 'sampler resource'.
Both are defined alongside 'uniform buffer' and 'storage buffer'.

PTAL.

2022-07-27 17:05 UTC, alan-baker approved these changes

2022-07-27 18:02 UTC, merged