Remove non-generic types from keywords list.
gpuweb/gpuweb pull request #3285
Opened 2022-08-04 15:09 UTC by dj2

This CL moves the types which do not have a generic component
from the keyword section section and makes them context
dependant.

This includes
 * bool
 * i32
 * u32
 * f32
 * f16
 * sampler
 * sampler_comparison
 * texture_depth_2d
 * texture_depth_2d_array
 * texture_depth_cube
 * texture_depth_cube_array
 * texture_depth_multisampled_2d

Issue: #3166, #3277

2022-08-04 16:34 UTC, dneto0 approved these changes

2022-08-04 16:36 UTC, dneto0 requested changes
They are  not context-dependent names.
"context dependent name" is a name that is used in a spot in the grammar that is *not* use identifier resolution.

But each of these occurs in a place that can have the name of a type, e.g. because it can be the name of a struct too.

2022-08-04 16:38 UTC, dneto0 commented
I think this patch has to say that these are predeclared types.  So they are actually identifiers that do resolve in the normal way.

2022-11-29 02:07 UTC, kdashg commented
Any progress here?

2022-11-29 15:48 UTC, closed without merging