[editorial] Replace uses of integral as a type
gpuweb/gpuweb pull request #3309
Opened 2022-08-10 21:00 UTC by alan-baker

Fixes #3133

* Replace uses of integral type with integer scalar in most places

2022-08-10 21:04 UTC, dj2 approved these changes

2022-08-10 21:40 UTC, dneto0 requested changes
one spurious word needs fixing

2022-08-10 21:40 UTC, dneto0 commented on wgsl/index.bs
> +        If |T| is an unsigned [=integer scalar=] scalar type, evaluates to:
delete the second scalar.

2022-08-11 21:53 UTC, dneto0 approved these changes
Thanks!

2022-08-11 21:53 UTC, merged