wgsl: clarify type equivalence of arrays with overridable element counts
gpuweb/gpuweb pull request #3442
Opened 2022-09-13 21:42 UTC by dneto0

Fixes: #3441

2022-09-13 21:43 UTC, ben-clayton approved these changes

2022-09-14 15:12 UTC, alan-baker requested changes

2022-09-14 15:12 UTC, alan-baker commented on wgsl/index.bs
> +    * They are both fixed-sized with element counts specified as identifiers [=resolve|resolving=]
```suggestion
    * They are both fixed-sized with element counts specified as identifiers [=resolves|resolving=]
```

2022-09-14 15:12 UTC, alan-baker commented on wgsl/index.bs
> +    // None of the following have the same type as `odds` and `evens.
```suggestion
    // None of the following have the same type as `odds` and `evens`.
```

2022-09-14 16:28 UTC, dneto0 commented on wgsl/index.bs
> +    // None of the following have the same type as `odds` and `evens.
I made them single quotes.

2022-09-14 18:37 UTC, alan-baker approved these changes

2022-09-15 14:57 UTC, merged