Make t descriptions consistent for texureSampleBias textureSampleGrad
gpuweb/gpuweb pull request #3452
Opened 2022-09-16 22:48 UTC by dneto0

Say "The sampled texture to sample." where "sampled" links to definition of sampled texture.

Fixes: #2892

2022-09-19 14:42 UTC, alan-baker requested changes
The sampled texture to sample seems redundant. Suggest just saying the sampled texture and having that be a link.

2022-09-19 14:42 UTC, alan-baker commented on wgsl/index.bs
> +  The [sampled](#sampled-texture-type) texture to sample.
```suggestion
  The [[#sampled-texture-type|sampled texture]].
```

2022-09-19 18:39 UTC, alan-baker commented
The last commit looks good, but something is up in that the overall PR shows 0 files changed.

2022-09-19 22:23 UTC, dneto0 commented
> The last commit looks good, but something is up in that the overall PR shows 0 files changed.

I've rebased and still the problem persists. ?!

2022-09-20 22:38 UTC, dneto0 commented
Checking top of tree HTML, this is fixed, somehow. 

git blame on top of tree shows #1204 as the commit in effect for the parameterization of `t` for both textureSampleBias and textureSampleGrad.   
So for whatever reason, the top of tree content is fine.
I'll close this PR, and close the issue as resolved.

2022-09-20 22:38 UTC, closed without merging