wgsl: Define "indeterminate value"
gpuweb/gpuweb pull request #3508
Opened 2022-10-05 19:31 UTC by dneto0

Also tightens ldexp such that it can generate shader-creation or pipeline-creation error when given an unsupported exponent argument.

Fixes: #2888

2022-10-05 19:33 UTC, dneto0 commented on wgsl/index.bs
> +    * If `e2` &gt; *bias* + 1
This is a tightening of the spec.  This was the only case where an indeterminate value could be generated as const-expr and override-expr, but it doesn't have to be that way.

That way we can make "indeterminate value" only apply to runtime expressions.

2022-10-05 19:54 UTC, dneto0 commented
To get this out there:
- the intent is describe an indeterminate value as 'frozen undef' or 'frozen poison' value.
- in particular it's fine to branch on an indeterminate value.

2022-10-11 18:23 UTC, dneto0 commented on wgsl/index.bs
> +          if extract == extract {
This holds because the type is i32.
For floats, the value could be NaN, and NaN is never equal to anything.
Expand this example to include NaN.

2022-10-11 18:24 UTC, dneto0 commented on wgsl/index.bs
> +          if extract == extract {
Feedback from @jimblandy

2022-10-11 20:27 UTC, dneto0 commented on wgsl/index.bs
> +          if extract == extract {
Addressed in the next commit.

2022-10-12 14:24 UTC, alan-baker requested changes

2022-10-12 19:24 UTC, dneto0 commented on wgsl/index.bs
> +using nonsense or unsupported values for its [=subexpressions=].
I'll remove the "nonsense" phrasing.

2022-10-12 19:26 UTC, dneto0 commented on wgsl/index.bs
> +value may be computed for each loop iteration.
done

2022-10-12 19:26 UTC, dneto0 commented on wgsl/index.bs
> +the indeterminate value produced at runtime may be a NaN value.
applied

2022-10-12 19:28 UTC, alan-baker approved these changes

2022-10-13 23:55 UTC, kdashg commented
<details><summary><a href="https://github.com/gpuweb/gpuweb/wiki/wgsl-2022-10-11-minutes#wgsl-define-indeterminate-value-3508">WGSL 2022-10-11 Minutes</a></summary>

* (to fix [#2888](https://github.com/gpuweb/gpuweb/issues/2888))
* DN: About runtime expressions when using nonsense values (or unsupported values) this is an undefined value except for each time you observe it it's the same value. It's a particular value at the execution. In LLVM terms. a frozen undef. No metastable aspect. Think that's what we're trying to capture for a value we don't want you to rely on but won't cause UB if branched as it has a specific answer
* KG: About uniformity?
* DN: No
* MM :Image if (x > 3) {} else if (x &lt; 3) {} do something else. Or hardware is capable of handling Nan. In this program if we made a nan (the frozen value is nan) then the program about is confusing. The program that would be have "correctly" is if x > 3 else {} that would behave correct in that one branch would happen. Were thinking about nan case and would like to be able to make nan as the frozen value (not necessarily all the time)
* DN: Yes, should be able to operate correctly however the translation isn't if x > 3 do something x &lt; 3 it's the negation of …
    * When x is float, this is how you should split up the “x&lt;3” into false and true cases.

		If (x &lt; 3.0)  { … }

 		If ( !(x&lt;3.0) ) { … }



* AB: Be careful about how you think about complete comparisons when doing ordered comparisons.
* MM: Official request is we would like frozen values to hold nans. Not proscribed but capable.
* DN: By my understanding the answer is yes. Nan is a valid bit values in metal and that is a valid bit pattern of the type and if it makes a nan it would be carried forward.
* KG: Maybe related, for nans is indeterminate value useful ot talk about? For implementations which don't support nan we said you get a different value back. Is this a useful framework to describe that? Say implementation does 0/0 and don't support nan, do we have any promises about that nan or can we say it's a frozen value? Or do we not have that.
* MM: The original calc is allowed to not produce nan, even if ieee says it should. If calculated nan and feed into another computation, that second computation may accept the nan, but not return nan, which is also against ieee. And the compiler is allowed to reorder computations, which means the “second” computation may actually appear earlier in the program source, or be hoisted up from a branch, or may not ever appear in the program source at all.
* JB: Looking at PR on line 4595 it has value extract which is the example of indeterminate value and says if extract == extract and has comment says always executed. If extract is nan, the reason this example is ok is because it's i32. If the example was f32 it would not be the case.
* DN: Correct, should expand to have float example with nans discussed.
* JB: 2 reasons compare could fail, 1- UB and 2- Nans involved. Don't want the first but want the second. Would be nice to have explicit.
* KG: So, want **PR changes**?
* JB: Yes, would like example expanded with note.
* DN: **Put note into PR**.

</details>

2022-10-14 22:17 UTC, jimblandy approved these changes

2022-10-14 22:17 UTC, jimblandy commented on wgsl/index.bs
> +       }
Yes - this is the kind of second example I had in mind.

2022-10-15 00:51 UTC, kdashg commented
@dneto0 merge when ready, just check out jimblandy's nits!

2022-10-18 23:37 UTC, merged