Limit the maximum statement nesting depth to 127
gpuweb/gpuweb pull request #3552
Opened 2022-10-26 16:16 UTC by alan-baker

Fixes #3527

* Limit the maximum nesting of statements to 127

2022-10-26 16:17 UTC, mehmetoguzderin approved these changes

2022-10-31 16:44 UTC, dneto0 requested changes

2022-10-31 16:44 UTC, dneto0 commented on wgsl/index.bs
> +    <tr><td>Maximum nesting depth of statements in a function<td>127
Nesting depth of statements isn't really defined.

It's mostly covered by compound_statement grammar element, but also: switch, loop, continuing each have their own handling.

Suggest changing this to

> Maximum nesting depth of brace-enclosed statements in a function.

That would mean, for example:

     fn foo() { /* depth 1*/  loop  { continuing { /*depth 3*/ break if true; }}} 

There's maybe an ambiguity about a switch body not being a statement? So then

> Maximum nesting depth of brace-enclosed statements or control flow in a function.

I don't know if that's better, or just confusing.   Your choice.

2022-11-01 19:28 UTC, dneto0 approved these changes

2022-11-01 19:29 UTC, merged