Add longer WGSL example to top of WGSL spec
gpuweb/gpuweb pull request #3842
Opened 2023-02-17 22:56 UTC by toji

The current example that the spec opens with is very short and doesn't give an good sense of the feel of the language as a whole:

```rs
@fragment
fn main() -> @location(0) vec4<f32> {
  return vec4<f32>(0.4, 0.4, 0.8, 1.0);
}
```

It's also not making use of vector aliases or similar syntactic sugar that can help influence developers opinion of the language.

A related problem is that if you open the spec and search for the word "loop" the you'll be directed to the "Loop Statement" section which contains this made-to-be-mocked-by-Twitter comparison:

<img width="366" alt="Screenshot 2023-02-17 at 2 44 49 PM" src="https://user-images.githubusercontent.com/805273/219811799-af4ddb0d-c11b-4f8b-9ff1-dba4accc72cb.png">

For developers that are looking at the WGSL spec for their first impressions of the language, these example code snippets don't leave a great first impression.

This PR updates the initial code example with more practical, real-world fragment shader which includes varyings, structs, bind groups, textures samples, and a loop. It uses aliases, type inference, and the for loop syntax to help the code read better. Hopefully it strikes a good balance of demonstrating many common features of the language without being overly complex.

(Also, I would recommend just dropping the "Example: GLSL Loop" section entirely, or reducing it to only having the GLSL example next to an example of WGSLs for loops.)

2023-02-18 00:24 UTC, dneto0 requested changes
Nits only: there are extraneous semicolons.

I like having a more practically interesting example.
I'm a little worried it's more than just "hello world".

I'd like another editor to chime in.

2023-02-18 00:24 UTC, dneto0 commented on wgsl/index.bs
> +    };
This terminating semicolon is not needed

2023-02-18 00:24 UTC, dneto0 commented on wgsl/index.bs
> +    };
Same here.

2023-02-18 00:31 UTC, alan-baker commented on wgsl/index.bs
> +        surfaceColor = surfaceColor + (baseColor * radiance * nDotL);
```suggestion
        surfaceColor += (baseColor * radiance * nDotL);
```

Optional

2023-02-18 00:33 UTC, alan-baker commented
I don't mind the complexity. It doesn't seem too bad to me.

2023-02-18 01:06 UTC, ben-clayton commented on wgsl/index.bs
> +      var surfaceColor = vec3(0.0);
nit: After writing a bunch of WGSL in various forms, I feel `vec3f(0)` is preferable. It's more explicit, and less to type.

2023-02-18 01:06 UTC, ben-clayton commented on wgsl/index.bs
> +        let radiance = lights.point[i].color * (1.0 / pow(dist, 2.0));
nit: `.0`'s here are unnecessary. And below.

2023-02-18 01:06 UTC, ben-clayton commented on wgsl/index.bs
> +      return vec4(surfaceColor, 1.0);
nit: `.0` is unnecessary.

2023-02-18 01:37 UTC, toji commented on wgsl/index.bs
> +        surfaceColor = surfaceColor + (baseColor * radiance * nDotL);
Oh! I didn't know that += worked now!

2023-02-18 05:25 UTC, dneto0 approved these changes
Nice!

2023-02-18 05:37 UTC, dneto0 requested changes
Need to fix the compilation problems.

2023-02-18 05:37 UTC, dneto0 commented on wgsl/index.bs
> +        let nDotL = max(dot(N, dir)), 0.0);
There is an extra parenthesis before the comma.
This doesn't parse.

2023-02-18 05:37 UTC, dneto0 commented on wgsl/index.bs
> +      point : array&lt;Light&gt;,
The Treesitter parser will check this example.  These &lt; and &gt; should be ordinary < and >

2023-02-18 05:37 UTC, dneto0 commented on wgsl/index.bs
> +      point : array&lt;Light&gt;,
Should be array<PointLight> because Light is not defined.

2023-02-18 05:37 UTC, dneto0 commented on wgsl/index.bs
> +      let baseColor = textureSample(baseColorTexture, baseColorSampler, uv);
uv is vec3f, but the texture is 2D

2023-02-18 05:37 UTC, dneto0 commented on wgsl/index.bs
> +        surfaceColor += (baseColor * radiance * nDotL);
No overload for vec4f * vec3f:  baseColor is vec4f, radiance is vec3f

2023-02-21 00:16 UTC, toji commented
Compilation problems fixed, thanks for helping spot them! (Didn't have the right toolchain installed initially so I couldn't do a full local build of the WGSL spec. Fixed that now.)

2023-02-21 00:26 UTC, ben-clayton commented on wgsl/index.bs
> +        let nDotL = max(dot(N, dir), 0.0);
`.0` unnecessary here too

2023-02-21 00:26 UTC, ben-clayton commented on wgsl/index.bs
> +        surfaceColor += (baseColor.rgb * radiance * nDotL);
Parentheses here unnecessary

2023-02-21 16:57 UTC, toji commented
Done and done. Thanks Ben!

2023-02-21 16:58 UTC, toji commented
(And for what it's worth, this PR has been quite educational for me! I've learned about a bunch of new syntactic sugar that I wasn't aware of before.)

2023-02-22 16:17 UTC, dneto0 approved these changes
Thanks!

2023-02-22 16:17 UTC, merged

2023-02-22 16:18 UTC, dneto0 commented on wgsl/index.bs
> +      var surfaceColor = vec3f(0);
This *could* be just `vec3f()` because no-arguments means it creates a zero value for the type.
But that's probably less readable in this case.