types, type-generators, enumerants are ordinary predeclared identifiers; not keywords or context-dependent names
gpuweb/gpuweb pull request #3859
Opened 2023-02-22 16:05 UTC by dneto0

Fixes: #3739 

    Add an example of shadowing predeclared objects

    Clarify shadowing of predeclared objects

    Rename template_arg_list to template_list
    
    Remove variable_qualifier in favour of template_list

    Remove references to context dependent names
    
    Make builtin params expressions
    
    Make var decl template params expressions

    Define enumerants, and the enumerant type
    
    - Many context-dependent names are now predeclared enumerants:
      - access mode
      - address space
      - interpolation type
      - interpolation sampling
      - texel format
      - built-in value names
    - Unreserve 'handle'

    Rename fully_qualified_ident to template_elaborated_ident

    Types and type-generating words are not keywords
    
    
    - Deliberately don't reserve types and type-defining words
    
    - Remove "type-defining keywords"
      A declaration can be a predeclared type-defining word.
    
    - Add concept of type-generator
      Type-generators can be predeclared.
    
    - Add a section to summarize predeclared types and type-generators.
    
    - Add access_mode to template_arg
    
    - Add TODO to make a "type" type

2023-02-22 21:43 UTC, dneto0 commented
FYI @ben-clayton @dj2

2023-02-22 21:43 UTC, dneto0 commented
This does not make bitcast an ordinary builtin function. That would build on this.

2023-02-23 04:14 UTC, mehmetoguzderin requested changes

2023-02-23 04:14 UTC, mehmetoguzderin commented on wgsl/index.bs
> +A declaration in is at <dfn noexport>module scope</dfn> if the declaration appears
Should this be `inside` than  `in`? `in is at` reads a bit hard

2023-02-23 04:14 UTC, mehmetoguzderin commented on wgsl/index.bs
> +For example, WGSL predeclares:
Maybe also `attributes`? Of course users can't define these but it might help the reader esp. when the syntax generalizes

2023-02-23 15:54 UTC, alan-baker requested changes

2023-02-23 15:54 UTC, alan-baker commented on wgsl/index.bs
> +## AllTypes Type ## {#alltypes-type}
Not a huge fan of this name, but I'm not sure of a better alternative.

2023-02-23 19:24 UTC, dneto0 commented
Rebased on main to pick up the cross-reference fixes

2023-02-23 21:58 UTC, mehmetoguzderin approved these changes

2023-02-24 15:05 UTC, alan-baker approved these changes

2023-02-24 15:29 UTC, merged