[editorial] Re-add splat constructors for vectors and matrices
gpuweb/gpuweb pull request #4020
Opened 2023-04-06 16:43 UTC by alan-baker

These were accidentally omitted from #3853

2023-04-06 17:00 UTC, mehmetoguzderin approved these changes
LGTM!

2023-04-06 19:59 UTC, dneto0 requested changes

2023-04-06 19:59 UTC, dneto0 commented on wgsl/index.bs
> +          @const @must_use fn mat2x2<T>(e : T) -> mat2x2<T>
The splat constructors didn't exist for matrices before.

2023-04-07 01:15 UTC, dneto0 approved these changes

2023-04-07 01:15 UTC, merged