Make GPUPipelineError constructor options optional
gpuweb/gpuweb pull request #4292
Opened 2023-09-15 12:46 UTC by foolip

The first argument is optional, so the second one also needs to be.

2023-09-15 12:50 UTC, beaufortfrancois commented
@Kangz That seems reasonable to me. What do you think?

2023-09-18 10:04 UTC, beaufortfrancois commented
As raised offline to @foolip, this spec PR needs to be updated as https://gpuweb.github.io/gpuweb/#dom-gpupipelineerror-constructor thinks `options` is always there:
 
```
            1. Set [=this=].{{GPUPipelineError/reason}} to |options|.{{GPUPipelineErrorInit/reason}}.
```

2023-09-18 17:56 UTC, foolip commented
What was the intention between the spec as written? Maybe both arguments should be required instead of both being optional. In Chrome both are actually required, as calling `new GPUPipelineError('bla')` throws "TypeError: Failed to construct 'GPUPipelineError': The provided value is not of type 'GPUPipelineErrorInit'."

2023-09-19 07:59 UTC, beaufortfrancois commented
I found https://github.com/gpuweb/gpuweb/issues/3709 which points to https://github.com/whatwg/webidl/pull/1211.
We may want to wait for @kainino0x's return to understand how we can fix this.

2023-10-04 17:27 UTC, mwyrzykowski approved these changes

2023-10-11 02:57 UTC, kainino0x requested changes
Yup, this is very much intentional, and per the example at https://webidl.spec.whatwg.org/#example-domexception-derived-interface. @beaufortfrancois found the correct context links. Please discuss with Domenic if you think this needs a change (see https://github.com/whatwg/webidl/pull/1211#issuecomment-1273274251).

2023-10-11 16:48 UTC, toji commented
Thanks for the background on that, Kai! Still looks strange to me but it's pretty clear that the WebIDL spec expects this kind of usage based on the linked example.

2023-11-20 23:30 UTC, closed without merging