Add syntax sugar for dereferencing composites
gpuweb/gpuweb pull request #4311
Opened 2023-10-02 17:40 UTC by alan-baker

Fixes #4114

* Add equivalent syntax for accessing components of a composite via pointer as when accessing via a reference
* Introduces a new language extension `pointer-composite-access`

2023-10-06 22:22 UTC, dneto0 requested changes
Suggestion for the wording describing the feature.

2023-10-06 22:22 UTC, dneto0 commented on wgsl/index.bs
> +      Supports dereferencing a pointer of [=composite=] type using the same
I think too many people will think "dereference" means perform the memory access.

Suggest

> Support [[#composite-value-decomposition-expr|composite-value decomposition expressions]] where the root expression is a pointer, yielding a reference.

>  For example, if `p` is a pointer to a structure with member `m`, then `p.m` is a reference to the memory locations for `m` inside the structure `p` points to.

> Similarly, if `pa` is a pointer to an array, then `pa[i]` is a reference to the memory locations for the i'th element of the array `pa` points to.

2023-10-09 12:34 UTC, mehmetoguzderin approved these changes
LGTM (while agreeing with the suggestion about dereference)

2023-10-10 19:14 UTC, dneto0 approved these changes
LGTM.  I would like to have @jimblandy weigh in on whether the feature description is descriptive enough of what's being added.

2023-11-23 05:18 UTC, jimblandy approved these changes
It seems like this falls out very nicely.

You may want to also update the language in "Valid and Invalid Memory References" as well, since named component expressions and indexing operations can now be applied to pointers.

Perhaps "Use Cases for References and Pointers" should also be updated - but it seems like that text is concerned with drawing distinctions. It's not clear anything needs to change here, although it's definitely in the neighborhood.

2023-11-23 05:21 UTC, jimblandy commented
@dneto0 I think it would make sense to extend this to swizzles as well. I think it would be surprising to people if `p.x` worked but not `p.xy`. The "Vector Multiple Component Selection" rules would not produce a reference, but they would implicitly dereference a pointer base.

2023-11-23 14:46 UTC, dneto0 commented
> @dneto0 I think it would make sense to extend this to swizzles as well. I think it would be surprising to people if `p.x` worked but not `p.xy`. The "Vector Multiple Component Selection" rules would not produce a reference, but they would implicitly dereference a pointer base. (To be clear, I still approve this PR.)

That's a really good point and a nice catch.  I agree that should be included.

Seems this upgrade should be in the "land it now and notify the committee" .

2023-11-23 15:37 UTC, alan-baker commented
I've added the multi-component selection changes and fixed a couple spots in valid and invalid memory references. PTAL.

2023-11-24 18:46 UTC, dneto0 approved these changes
LGTM. Thank you!

2023-11-24 18:54 UTC, merged